### ISSUE TITLE
Mac address change after flashing kernel

### ISSUE THREAD

**Issue by kotzir** [franciscofranco/tissot#1]
Hello franco, could you please add this commit to the next update? [(https://github.com/TheScarastic/android_kernel_xiaomi_msm8953/commit/2d9cdc3b435f97daaa6e73f862eb6af151bf0f6f)](url)
It will prevent the Mac Addresses from changing

**Comment by ghost** [comment]
Are you sure about it?

**Comment by kotzir** [comment]
Yes, after flashing Franco's kernel my MAC Addresses change. Both Bluetooth and WiFi work, but with different MAC addresses.

**Comment by ghost** [comment]
But this did not work out actually!
